### ISSUE TITLE
Error During use

### ISSUE THREAD

**Issue by abh3po** [bharadwaj-raju/libdesktop#4]
```
from xdg import DesktopEntry                                                                                        
ImportError: No module named 'xdg' 
```
Full Traceback:

```
Traceback (most recent call last):                                                                                        
File "UIP.py", line 1, in <module>                                                                                        
from scheduler import scheduler                                                                                       
File "/mnt/c/Project/UIP/scheduler.py", line 1, in <module>                                                            
from  libdesktop.wallpaper import set                                                                                 
File "/usr/local/lib/python3.4/dist-packages/libdesktop/__init__.py", line 8, in <module>                  
from .linux_exec_desktop_file import linux_exec_desktop_file                                                          
File "/usr/local/lib/python3.4/dist-packages/libdesktop/linux_exec_desktop_file.py", line 24, in <module>                
 from xdg import DesktopEntry                                                                                       
 ImportError: No module named 'xdg'
```

**Comment by bharadwaj-raju** [comment]
You seem to be having a very old version of libdesktop installed.

Download the latest and run `sudo make install`.

Also, `xdg` is a Python module installed on almost all Linux desktops, but libdesktop no longer has a dependency on it.

**Comment by abh3po** [comment]
i used the version on pip? is it not upto date?

**Comment by bharadwaj-raju** [comment]
Well, no. I shall update it regularly once libdesktop becomes stable.

Actually, even the pip version is _much_ more recent than that.
